cuisine_types = [
    'german', 'japanese', 'vegetarian', 'french', 'african', 'american', 
    'barbecue', 'czech', 'chinese', 'thai', 'mexican', 'indian', 
    'cafe', 'pizza', 'italian'
]

restaurant_info = [
    ['german', "Bavarian Biergarten", '3', '3', '22 Teutonic Ave.'],
    ['japanese', 'Sakura Sushi', '4', '5', '8 Hawthorne Ln.'],
    ['vegetarian', 'Veggie Heaven', '2', '1', '22A King West'],
    ['french', 'Le Gourmet', '5', '4', '2 South Park Dr.'],
    ['african', 'Mama Africa', '3', '2', '1566 Maple Rd.'],
    ['american', "Bob's Diner", '4', '3', '96 College Blvd.'],
    ['barbecue', 'Smokey Joe\'s', '3', '2', '623 Industrial Rd.'],
    ['czech', 'Bohemian House', '1', '4', '5567 Queen-Mary Rd'],
    ['german', 'Wursthaus', '3', '5', '402 College Blvd.'],
    ['chinese', 'Golden Dragon', '2', '4', '38 Teutonic Ave.'],
    ['thai', 'Thai Spice', '4', '3', '12 Oak St.'],
    ['mexican', 'El Camino', '5', '2', '47 Fiesta Blvd.'],
    ['indian', 'Curry Palace', '3', '4', '101 Spice Rd.'],
    ['cafe', 'Morning Brew', '4', '1', '123 Main St.'],
    ['pizza', 'Pizza Paradise', '5', '3', '77 Sunset Blvd.'],
    ['italian', 'Mamma Mia', '4', '5', '88 Pasta Ln.'],
    ['german', 'Bierhaus', '2', '4', '50 Market St.'],
    ['japanese', 'Tokyo Grill', '3', '3', '14 Maple Ave.'],
    ['vegetarian', 'Herbivore', '5', '2', '56 Plant Rd.'],
    ['french', 'Chez Pierre', '4', '5', '23 Elm St.'],
    ['african', 'Safari Bites', '3', '3', '77 Jungle Rd.'],
    ['american', 'Diner Deluxe', '4', '2', '18 Elm St.'],
    ['barbecue', 'BBQ Pit', '5', '4', '99 Smoke Rd.'],
    ['czech', 'Pilsner Place', '2', '3', '34 Brewery Ln.'],
    ['chinese', 'Red Lantern', '3', '5', '55 Dragon St.'],
    ['thai', 'Bangkok Bites', '4', '4', '90 King St.'],
    ['mexican', 'Taco Haven', '2', '1', '61 Burrito Blvd.'],
    ['indian', 'Spice Route', '5', '2', '82 Curry St.'],
    ['cafe', 'Bean There', '3', '1', '11 Coffee Ln.'],
    ['pizza', 'Cheese Wheel', '4', '4', '44 Pizza Pl.'],
    ['italian', 'Pasta Fresca', '5', '3', '66 Italia Rd.'],
    ['german', 'Munich Delights', '3', '5', '29 Bavarian St.'],
    ['japanese', 'Samurai Sushi', '4', '3', '17 Samurai Ln.'],
    ['vegetarian', 'Leafy Greens', '2', '1', '78 Vegan Blvd.'],
    ['french', 'Bistro Bella', '4', '5', '9 French St.'],
    ['african', 'Zambezi Eats', '3', '2', '25 Safari Dr.'],
    ['american', 'Route 66 Diner', '5', '4', '66 Highway Rd.'],
    ['barbecue', 'Rib Shack', '3', '2', '101 Grill St.'],
    ['czech', 'Boho Bistro', '4', '3', '22 Prague Ln.'],
    ['chinese', 'Great Wall', '5', '4', '13 Great St.'],
    ['thai', 'Thai Delight', '2', '3', '6 Spice Ave.'],
    ['mexican', 'Cantina', '3', '2', '11 Taco Ln.'],
    ['indian', 'Tandoori House', '4', '5', '99 Tandoori St.'],
    ['cafe', 'Latte Love', '2', '1', '7 Bean Blvd.'],
    ['pizza', 'Slice of Heaven', '3', '3', '21 Pizza St.'],
    ['italian', 'Bella Italia', '4', '5', '5 Pasta Blvd.']
]
